/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.someip 3.1.12.v201706201046.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/

#ifndef V1_SIMPLECALCULATOR_CALCULATORINTERFACE_Calculator_SOMEIP_DEPLOYMENT_HPP_
#define V1_SIMPLECALCULATOR_CALCULATORINTERFACE_Calculator_SOMEIP_DEPLOYMENT_HPP_


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace SimpleCalculator {
namespace CalculatorInterface {
namespace Calculator_ {

// Interface-specific deployment types
typedef CommonAPI::SomeIP::EnumerationDeployment<int32_t> DIVISION_ERRORDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<int32_t> MetadataTypeDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<int32_t> MetadataFormatDeployment_t;
typedef CommonAPI::SomeIP::ArrayDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> MyArray01Deployment_t;
typedef CommonAPI::SomeIP::ArrayDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>
> MyArray02Deployment_t;
typedef CommonAPI::SomeIP::ArrayDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>
> MyArray03Deployment_t;
typedef CommonAPI::SomeIP::ArrayDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>
> MyArray04Deployment_t;
typedef CommonAPI::SomeIP::ArrayDeployment<
    CommonAPI::SomeIP::ByteBufferDeployment
> MyArray05Deployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataTypeDeployment_t,
    ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataFormatDeployment_t,
    CommonAPI::SomeIP::StringDeployment,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>
> MetadataElementDeployment_t;
typedef CommonAPI::SomeIP::ArrayDeployment<
    CommonAPI::SomeIP::StructDeployment<
        ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataTypeDeployment_t,
        ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataFormatDeployment_t,
        CommonAPI::SomeIP::StringDeployment,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    >
> MetadataElementListDeployment_t;

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployment

// Broadcast-specific deployments

} // namespace Calculator_
} // namespace CalculatorInterface
} // namespace SimpleCalculator
} // namespace v1

#endif // V1_SIMPLECALCULATOR_CALCULATORINTERFACE_Calculator_SOMEIP_DEPLOYMENT_HPP_
